#!/bin/bash

# Create legacy libpangox symlinks for software that still links against the
# old soname even when only libpangoxft is installed.
for source_lib in /usr/lib/libpangoxft-*; do
    [ -e "$source_lib" ] || continue
    compat_lib="${source_lib/libpangoxft/libpangox}"

    if [ ! -e "$compat_lib" ]; then
        ln -s "$source_lib" "$compat_lib" 2> /dev/null
    fi
done
