#!/usr/bin/bash

network_file=/etc/libvirt/qemu/networks/default.xml

# Adiciona os grupos libvirt e libvirt-qemu a todos usuarios acima de 1000
for user in $(awk -F':' '{ if ($3 >= 1000 && $1 != "nobody") print $1 }' /etc/passwd); do
    usermod -a -G libvirt $user
    usermod -a -G libvirt-qemu $user
    sudo -u $user XDG_RUNTIME_DIR=/run/user/$(id -u $user) gsettings set org.virt-manager.virt-manager xmleditor-enabled true
    sudo -u $user XDG_RUNTIME_DIR=/run/user/$(id -u $user) gsettings set org.virt-manager.virt-manager system-tray true
done

# Backup do default.xml
if [ ! -e "${network_file}.bkp" ] && [ -e "$network_file" ];then
    cp "$network_file" "${network_file}.bkp"
fi

# Verifica se o range de ip usado pelo libvirt não está sendo usado por outro rede
libvirtNetRange=$(grep -oP "(?<=ip address=')[0-9]+\.[0-9]+\.[0-9]+" "$network_file")
if [ -n "$(ip -o -4 a | grep $libvirtNetRange)" ]; then
    newLibvirtNetRange=$(awk -F. '{print $1 "." $2 "." $3+1}' <<< $libvirtNetRange)
    sed -i "s/$libvirtNetRange/$newLibvirtNetRange/g" "$network_file"
fi

# Aceita bridge em todas as redes
if [ -e /etc/qemu/bridge.conf ] && [ -z "$(grep 'allow all' /etc/qemu/bridge.conf)" ]; then
    echo "allow all" | tee -a /etc/qemu/bridge.conf > /dev/null
fi

# Configura, starta e coloca no autostart a rede do libvirt
network=$(LANG=C virsh net-list | grep default)
if [ -z "$network" ];then
    virsh net-define "$network_file"
fi
network=$(LANG=C virsh net-list | grep default)
if [ "$(awk '{print $2}' <<< $network)" != "active" ];then
    virsh net-start default
fi
network=$(LANG=C virsh net-list | grep default)
if [ "$(awk '{print $3}' <<< $network)" != "yes" ];then
    virsh net-autostart default
fi

# Enable and start libvirtd
systemctl enable --now libvirtd.service
