#!/bin/bash

if [ -e /usr/lib/systemd/system/nginx.service ] || [ -e /etc/systemd/system/nginx.service ]; then
    systemctl disable nginx.service > /dev/null 2>&1 || true
    systemctl stop nginx.service > /dev/null 2>&1 || true
fi
