#!/bin/bash

#Temporary fix to Spectacle
if [ -e "/usr/share/applications/org.kde.spectacle.desktop" ]; then
    sed -i 's|Exec=/usr/bin/spectacle|Exec=QMLSCENE_DEVICE=softwarecontext /usr/bin/spectacle|g' /usr/share/applications/org.kde.spectacle.desktop
fi

#Change StartLimitBurst to 20, in one minute, when change theme from BigLinux panel count one Burst
if [ -e "/usr/lib/systemd/user/plasma-plasmashell.service" ]; then
    sed -i 's|StartLimitBurst=3$|StartLimitBurst=20|g' /usr/lib/systemd/user/plasma-plasmashell.service
fi




for i  in  $(ls /usr/lib/modules | grep -v extramodules 2> /dev/null); do

    if [ -e "/lib/modules/${i}/build" ]; then

        if [ ! -e "/usr/src/linux-headers-${i}" ]; then
            ln -sf "/lib/modules/${i}/build" "/usr/src/linux-headers-${i}" 2> /dev/null
        fi

        if [ ! -e "/usr/lib/modules/${i}/build/version" ]; then
            ln -s "/usr/lib/modules/${i}/extramodules/version" "/usr/lib/modules/${i}/build/version" 2> /dev/null
        fi
        
        # Remove if link is broken
        if [ ! -e "/lib/modules/${i}/build/version" ]; then
            rm -f /lib/modules/${i}/build/version
        fi

        # Remove if link is broken
        if [ ! -e "/usr/src/linux-headers-${i}" ]; then
            rm -f /usr/src/linux-headers-${i}
        fi

        # Remove folder if empty
        rmdir --ignore-fail-on-non-empty /lib/modules/${i}/build
        rmdir --ignore-fail-on-non-empty /lib/modules/${i}

        
    fi
done

if [ -e "/usr/share/hplip/base/password.py" ]; then
    sed -i "s|os_name = platform.dist()\[0]|os_name = 'manjarolinux'|g" /usr/share/hplip/base/password.py 2> /dev/null
fi

if [ -e "/usr/lib/libicuio.so" ]; then
    ln -s /usr/lib/libicuio.so /usr/lib/libicuio.so.suse65.1 2> /dev/null
    ln -s /usr/lib/libicui18n.so /usr/lib/libicui18n.so.suse65.1 2> /dev/null
    ln -s /usr/lib/libicuuc.so /usr/lib/libicuuc.so.suse65.1 2> /dev/null
    ln -s /usr/lib/libicudata.so /usr/lib/libicudata.so.suse65.1 2> /dev/null
fi

if [ ! -e "/usr/lib/libmpv.so.1" ]; then
    ln -s /usr/lib/libmpv.so /usr/lib/libmpv.so.1 2> /dev/null
fi

if [ ! -e "/usr/lib/libvpx.so.7" ]; then
    ln -s /usr/lib/libvpx.so /usr/lib/libvpx.so.7 2> /dev/null
fi

if [ ! -e "/usr/lib/libtiff.so.5" ]; then
    ln -s /usr/lib/libtiff.so /usr/lib/libtiff.so.5 2> /dev/null
fi

exit 0
