#!/bin/bash

# Remove only compatibility links created by the install helper.
for source_lib in /usr/lib/libpangoxft-*; do
    [ -e "$source_lib" ] || continue
    compat_lib="${source_lib/libpangoxft/libpangox}"

    if [ -L "$compat_lib" ]; then
        rm "$compat_lib"
    fi
done
