#!/bin/bash

for i  in  $(ls /usr/lib/modules | grep -v extramodules); do

    if [ -e "/lib/modules/${i}/build" ]; then

        if [ ! -e "/usr/src/linux-headers-${i}" ]; then
            ln -sf "/lib/modules/${i}/build" "/usr/src/linux-headers-${i}" 2> /dev/null
        fi

        if [ ! -e "/usr/lib/modules/${i}/build/version" ]; then
            ln -s "/usr/lib/modules/${i}/extramodules/version" "/usr/lib/modules/${i}/build/version" 2> /dev/null
        fi

    fi
done

if [ -e "/usr/share/hplip/base/password.py" ]; then
    sed -i "s|os_name = platform.dist()\[0]|os_name = 'manjarolinux'|g" /usr/share/hplip/base/password.py
fi
