#!/bin/bash

if ! getent group docker > /dev/null; then
    groupadd docker
fi

for user in $(awk -F':' '{ if ($3 >= 1000 && $1 != "nobody") print $1 }' /etc/passwd); do
    usermod -aG docker "$user"
done

systemctl daemon-reload
systemctl start docker.service
systemctl enable docker.service

newgrp docker
