#!/bin/bash

if [ -e /usr/lib/systemd/system/nginx.service ] || [ -e /etc/systemd/system/nginx.service ]; then
    systemctl enable nginx.service > /dev/null 2>&1 || true
    systemctl start nginx.service > /dev/null 2>&1 || true
fi
